# Configuration for the production environment

ktor { # this block will auto-reading by ktor lib
    development = true

    deployment {
        port = 8080
        environment = prod
    }
    application {
        modules = [com.github.nepyh.rooter.BootstrapperKt.appEntryModule]
    }
}

cors {
    allowedHosts = ${ALLOWED_HOSTS}
    maxAgeSeconds = 3600
}

database {
    jdbcUrl = ${JDBC_URL}
    dbUser = ${DB_USER}
    dbPassword = ${DB_PASSWORD}
    dbMaxPoolSize = ${DB_MAX_POOL_SIZE}
}

storage {
    type = local
    // TODO this is temporary setting
    baseDir = run/store
    baseUrl = /api/files
    baseRoute = files
}

jwt {
    secret = ${JWT_SECRET}
    issuer = ${JWT_ISSUER}
}

nice {
    apiKey = ${NICE_API_KEY}
    baseUrl = "https://open.neis.go.kr/hub"
}
